server:
  port: 8081

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/yeb?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 940510
    #springboot默认使用hikari数据库连接池
    hikari:
      #连接池名
      pool-name: DateHikari
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，30分钟
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，30分钟
      max-lifetime: 180000
      #连接超时时间，30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis配置
  redis:
    timeout: 10000
    host: 192.168.211.128
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，，默认-1
        max-wait: 10000
        #最大空闲连接数
        max-idle: 200
        #最小空闲连接数
        min-idle: 5

  #rabbitmq配置
  rabbitmq:
    #用户名
    username: admin
    #密码
    password: admin
    #服务器地址
    host: 192.168.211.128
    #端口
    port: 5672
    #消息确认回调
    publisher-confirm-type: correlated
    #消息失败回调
    publisher-returns: true

mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.myself.server.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

#mybatis sql语句以debug的形式打印（方法接口所在包）
logging:
  level:
    com.myself.server.mapper: debug

#jwt
jwt:
  #存储的请求头
  tokenHeader: Authorization
  #加密解密的密钥
  secret: yeb-secret
  #超时期限（7天）
  expiration: 604800
  #头部信息
  tokenHead: Bearer