server:
  port: 8082

spring:
  #邮件配置
  mail:
    #服务器地址
    host: smtp.163.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: utf-8
    #授权码
    password: ANROOYLARXLVFJOX
    #发送者邮箱
    username: jiawei_shen@163.com
    #端口
    port: 25

  #rabbitmq配置
  rabbitmq:
    #用户名
    username: admin
    #密码
    password: admin
    #服务器地址
    host: 192.168.211.128
    #端口
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

  #redis配置
  redis:
    timeout: 10000
    host: 192.168.211.128
    port: 6379
    database: 0
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，，默认-1
        max-wait: 10000
        #最大空闲连接数
        max-idle: 200
        #最小空闲连接数
        min-idle: 5